### ISSUE TITLE
Bette styling

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/js_arules#1]
I should say, it has no style at all.
So it looks horrible, and I need a helping hand. 
Supporting Mobile phones is good but not the target.
The perfect touch would be to also style association rules results !

**Comment by wwwilliams** [comment]
Can I help?

**Comment by bacloud14** [comment]
Oh it would be great ! Styling is yours !

**Comment by wwwilliams** [comment]
I made some changes. I'm not the best at this but I tried to offer some value. I am open to suggestions for improving. Thanks. Let me know what you think.

**Comment by bacloud14** [comment]
A big change already ! yet to come I hope, I will put some effort on this to visualize association rules ! If you can help you are very welcome Wiliams! So let this issue open longer,
Many thanks !!

**Comment by bacloud14** [comment]
I hope you could experiment on your bank bill, or shopping list by the way, and probably could find some secrets ;)

**Comment by wwwilliams** [comment]
What do you mean? Where are you from if you don’t mind me asking?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wwwilliams** [comment]
What are you working on in particular? It might help to have a readme file available. I enjoyed helping and will do so workload permitting in the future.

**Comment by bacloud14** [comment]
I will definitely open other issues. I suggest that you read about association rules if you do not know about. It is a very simplistic association learning algorithm that is very useful to discover hidden causalities in categorical data. There is no implementation that is deployed in a browser as far as I know. Client would not share (upload) their csv files, this is  why I thought this would be secure and useful.
I also have another tiny JS app Interactive_arrays. I am really into native JS applications.
Definitely, I will join a readme although the index.html already speaks of itself.

**Comment by bacloud14** [comment]
The other "fancy" styling, would be to visualize the association rules. It is straightforward subject to weighted graphs;
I am checking how to apply this !

**Comment by bacloud14** [comment]
weighted graphs are JS omnipresent, although, I want the lightest implementation, not to include a whole D3.js like library !

**Comment by wwwilliams** [comment]
I was not familiar with Association Rules but I am now. :) I think you're wanting a D3.js library integrated in your code (or perhaps another type of library). If so, I can help with this if you like. I'll just be on the lookout for other issues. Thanks a lot for the help.

**Comment by bacloud14** [comment]
I do not really know what I want, although I represented results in a
simple weighted couples. I think any weighted graph library would be good.

Kind regards

**Comment by bacloud14** [comment]
Yes D3js seems the right way like this example:
https://flowingdata.com/2012/08/02/how-to-make-an-interactive-network-visualization/

**Comment by wwwilliams** [comment]
I pushed a new code that has the D3js library in it. Unfortunately I wasn't able to do anything fancy with it as I'm unfamiliar with the library.

**Comment by bacloud14** [comment]
Partially resolved thanks to https://github.com/bacloud14/js_arules/commit/edd6e72843867c59f697570617841d6768b63115 
I will invest time for graph visualization.
